### ISSUE TITLE
Referencing sub-collections

### ISSUE THREAD

**Issue by DavidPhilip** [mikkopaderes/ember-cloud-firestore-adapter#70] opened 2018-10-21 15:55 UTC
One can build references and hence save into sub-collections like:
```
this.get('store').findRecord('user', 'user_a').then((user) => {
  this.get('store').createRecord('post', {
    body: 'New Post Body',
    title: 'New Post Title',
    author: user
  }).save({
    adapterOptions: {
      buildReference(db) {
        return db.collection('users').doc('user_b').collection('feeds');
      }
    }
  });
});
```
But if I set such a sub-collection doc as a relation - like in the above example instead of `post -> user` you would set `user -> post` - it will always be serialized as a root-collection (see https://github.com/rmmmp/ember-cloud-firestore-adapter/blob/master/addon/serializers/cloud-firestore.js#L91).

Is this intentional or a bug?

**Comment by rmmmp** [comment] 2018-10-21 17:44
That is intentional.

Having models under a sub-collection could cause duplication in Ember Data. Thus, there should be one source of truth for where the adapter would get the model record from.

In your example above, one way to design things from a NoSQL perspective is that all feeds are merely a duplicate of a post. It's useful that way since it's impractical to search for a user's feed under the `posts` collection due to variety of factors of when a post should be a feed to a user.

In order to provide data faster, we can simply query from a user's feeds sub-collection. However, for data accuracy purposes, we'll do an additional fetch for the original post and use it instead of the duplicate feed.

**Comment by DavidPhilip** [comment] 2018-10-21 17:55
Ok maybe this was a bad example as it is working for the point you are trying to make here but not mine 😄

Assume we have a `team` and a `waypoint` model:
```
// Team
Model.extend({
  start: belongsTo('waypoint'),
  end:   belongsTo('waypoint')
});
```

I want to save the `waypoints` under `teams/:id/waypoints` as they would only be referenced by the  associated team. I see no reason to expose them on root level as I also don't need to query them. Would you consider this a valid use-case?

**Comment by rmmmp** [comment] 2018-10-22 03:08
Yup that's a valid use-case. However, sub-collection doesn't enforce uniqueness in terms of the ID. You can have `Waypoint` model record of ID `waypoint_a` under multiple sub-collections. Which one should Ember Data store and keep updates on should that ever happen?

As an ugly workaround, you can manually query using the native Firestore API through the `Firebase` service. Then use `store.findRecord()` on each one so you could have it in the `Store`.

```javascript
import { inject as service } from '@ember/service';
import Controller from '@ember/controller';

export default Controller.extend({
  firebase: service('firebase'),

  async foo() {
    const db = this.firebase.firestore();
    const waypointQuerySnapshot = await db.collection('teams/team_a/waypoints').get();

    return Promise.all(
      waypointQuerySnapshot.docs.map(doc => this.store.findRecord('waypoint', doc.id))
    );
  }
});
```

**Comment by rmmmp** [comment] 2018-10-23 05:48
I understand your use-case but it may not be the same for the others. Your business logic might prevent saving the same ID in a different sub-collection but there's really nothing stopping a bad person from doing it as we can't enforce it in the Firestore Security Rules.

If we want to support this, I think having an API for it would be the way to go. Probably passing an property in the `adapterOptions` to indicate that it won't cross-fetch in a root node. What do you think?

For what it's worth, I'm not forcing you to go down that route. You can go for sub-collection if that's how you want to structure it. There's nothing wrong with it honestly.

**Comment by DavidPhilip** [comment] 2018-10-23 06:01
I understand, that's an aspect I haven't thought of yet. I'll let it sink and will get back to you, thanks!

**Comment by rmmmp** [comment] 2018-10-23 07:07
It's important that we don't structure our data for Ember Data so I might go ahead and implement this. Plus, it's been discussed multiple times already so I guess there's really a lot of use-case for it.

**Closed** 2018-12-09 13:52 UTC
Labels: question

**Comment by DavidPhilip** [comment] 2018-12-10 10:33
Thanks a bunch for this 👍

I went on and implemented my own solution in the end, also supporting one-to-many references e.g. I will integrate your update there as well and make a PR when it's solid.
