### ISSUE TITLE
firebase-app.js: Overwriting FirebaseError base field "name" can cause unexpected behavior.

### ISSUE THREAD

**Issue by alexmasita** [mikkopaderes/ember-cloud-firestore-adapter#98] opened 2019-06-17 14:15 UTC
Hi @mikkopaderes.  Thanks for your continued awesome work on this.  I am getting the above warning in my console when I implement the ESA authentication solution as seen in your guides here.  Everything seems to work perfectly but that warning might signify a problem that might stump me later.  Is this a known issue from your end? 

You can see from the following screenshot: [Console View](http://prntscr.com/o2xyk1) that even with the warning, the session's isAuthenticated property is true and I am able to get session authenticated data.

I am also getting odd behaviour where on my (fastboot) app refresh, the session appears not to stay authenticated as it goes to the authentication page.  I have enabled fastboot support according to the Ember Simple Authentication documentation by using only the cookie session store but to no avail.  When I disable fastboot, the session is restored correctly.  Perhaps you can advise me on this as well if you can?

Let me know.

**Comment by mikkopaderes** [comment] 2019-06-17 16:29
I'll check to see if I can reproduce the warning on my side.

As for fastboot, I couldn't do anything with it before as Firebase needed to support cookie based auth for it to work—they use JWT for auth.

I'm not sure if they support cookie auth now. I'll have to check back on it.

**Comment by mikkopaderes** [comment] 2019-06-17 18:15
The warnings seems to have been introduced in Firebase 6.0.0. It happens when we call [`firebase.app()`](https://github.com/mikkopaderes/ember-firebase-service/blob/0becb662fe574b5a9fb70a6f30d87430f5197afb/addon/services/firebase.js#L13) and no Firebase instance exists yet.

I'm not sure what the impact is yet. If any, this just may be some false warning from Firebase which they should fix if true.

**Comment by alexmasita** [comment] 2019-06-18 14:25
> I'll check to see if I can reproduce the warning on my side.
> 
> As for fastboot, I couldn't do anything with it before as Firebase needed to support cookie based auth for it to work—they use JWT for auth.
> 
> I'm not sure if they support cookie auth now. I'll have to check back on it.

Thanks for looking into this.  Regarding fastboot firebase session support, I was under the impression that the actual authentication only happens once on the client side.  Subsequent access to the authenticated routes would then only have to rely on the established session which is stored in the cookie store until invalidated.  

Unless I understood incorrectly, I believe ESA resolved session access in fastboot by implementing the ember-cookie addon which runs on both the client and server.  As such, shouldn't the session be restored from this cookie on the fastboot server without hitting the firebase authentication apis again?

**Comment by alexmasita** [comment] 2019-06-18 14:28
> The warnings seems to have been introduced in Firebase 6.0.0. It happens when we call [`firebase.app()`](https://github.com/mikkopaderes/ember-firebase-service/blob/0becb662fe574b5a9fb70a6f30d87430f5197afb/addon/services/firebase.js#L13) and no Firebase instance exists yet.
> 
> I'm not sure what the impact is yet. If any, this just may be some false warning from Firebase which they should fix if true.

Thanks for confirming this.  I guess we will just have to keep a look out for any eventuality on this.

**Comment by mikkopaderes** [comment] 2019-06-18 15:59
I can't recall if ESA has their own cookies being set. I'm sure though that we aren't using it if any and should not even if we can. This is because Firebase auth tokens are short lived so we always need to check the auth state and refresh the tokens.

I've seen a new [guide](https://firebase.google.com/docs/auth/web/service-worker-sessions) in Firebase that might solve this use-case but I'll have to look into it more and see how I could best implement this in the addon. Basically, it would involve service workers.

**Comment by alexmasita** [comment] 2019-06-18 17:17
I gotcha.  Will also look into it and see if there is anything I could do to help.  Thank you.

**Comment by alexmasita** [comment] 2019-06-18 18:45
I saw that the ESA guides show how to set up the cookie store exclusively when you are setting up your fastboot app somewhere on the read me.  But be that as it may, I just looked at the firebase token lifetime and I see it generally takes an hour to expire which I thought is not such a short time to really worry about refreshing because by an hour, at least in my app, the job will have been long done.  

The other thought that I have is, the fastboot server is only necessary at first boot after which the client takes over.  I think the hour it takes to expire the token will be long enough not to feel disturbing to a user when it does expire and forces a re-authentication.  If the other service worker solution seems like it will take time, would it be feasible to patch this addon to work with token even just for an hour in the mean-time while we look for a long time solution?

**Comment by mikkopaderes** [comment] 2019-06-19 03:37
If your users doesn't visit your app for more than an hour and revisit again, they'll end up hitting fastboot with an authenticated state again because the token is already expired. This might not be a good user experience for you.

So really, even if I add cookie support, I think the service worker is what you'd want.

**Comment by mikkopaderes** [comment] 2019-06-19 04:19
I've created a spin-off issue #99 as it's out of scope of this issue. I'll be closing this now as the question in the issue title has already been addressed. We can re-open this if necessary.

**Closed by mikkopaderes** 2019-06-19 04:19 UTC

**Comment by alexmasita** [comment] 2019-06-19 18:55
Thank you.  Will be great to continue to work towards a solution on the other thread.  See you there.
