### ISSUE TITLE
Realtime Listener Error: Cannot destructure property 'unsubscribe' of 'this.queryListeners[queryId]' as it is undefined

### ISSUE THREAD

**Issue by ceit-each** [mikkopaderes/ember-cloud-firestore-adapter#250] opened 2022-11-07 09:09 UTC
Coming across the issue shown in the images below quite regularly. When it happens, it removes the listener from the affected query. 

In our case, it occurs when a cloud function updates data which is being queried in app with `isRealtime = true`. But I can recreate by simply writing any data to multiple docs in the query via a script.

<img width="656" alt="Screenshot 2022-11-07 at 08 05 23" src="https://user-images.githubusercontent.com/48324326/200258504-0049c7e6-255e-42d7-8613-90ad3a0f66c1.png">

<img width="574" alt="Screenshot 2022-11-07 at 08 05 49" src="https://user-images.githubusercontent.com/48324326/200258736-234c8304-bf94-4944-968b-f00b9dae7ddc.png">

The Query:
```
this.store.query('collectionName', {
  isRealtime: true,
  filter: (ref) => query(ref, where('field1', '==', 'value'), orderBy('field2')),
});
```

The node script that triggers the error:
```
let documents = await db.collection('collectionName').where('field1', '==', 'value').limit(2).get();
let promises = [];
documents.forEach(document => {
  promises.push(
    document.ref.update({
      dummy: new Date()
    })
  );
});
await Promise.all(promises);
```

And interestingly if the script is changed to await each update, the error doesn't seem to occur:
```
for (let document of documents.docs) {
  await document.ref.update({
    dummy: new Date()
  });
}
```

**Expected behavior**
For there to be no error and the listener to not be removed.

**Tooling versions (please complete the following information):**
 - Ember: 4.7.0
 - Ember Data: 4.7.1
 - Ember Cloud Firestore Adapter: 2.3.0
 - Firebase: 9.6.8

**Comment by mikkopaderes** [comment] 2022-11-12 06:19
I can imagine how this can be an error and can be caused by having multiple documents updated with very little interval. The `for-of` loop doesn't trigger the issue most likely because it waits for the `.update()` to finish before moving on to the next loop unlike your `.forEach()` example.

I can provide a fix for this, but if you can, you might to batch your writes if it's possible for your use-case.

**Closed** 2022-11-12 07:07 UTC

**Comment by ceit-each** [comment] 2022-11-12 21:35
Nice one, thanks for looking at this! 
No error for me with the fix.
